// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI0TMgEG-afSaihIi4XMMZYl3UVFn9HV0',
    appId: '1:270419631491:web:f2302bf1b8870a3b26eab6',
    messagingSenderId: '270419631491',
    projectId: 'readysethire-db',
    authDomain: 'readysethire-db.firebaseapp.com',
    storageBucket: 'readysethire-db.firebasestorage.app',
    measurementId: 'G-5KYCTGT16S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuAogH92snCA7YAFNhAKtas3WLqOBrkiE',
    appId: '1:270419631491:android:306f6ec5cdb30d4b26eab6',
    messagingSenderId: '270419631491',
    projectId: 'readysethire-db',
    storageBucket: 'readysethire-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-Ir-HKBjR5kOZoq_tRiFgI0_eO1M2Zg',
    appId: '1:270419631491:ios:fb864aee298f508726eab6',
    messagingSenderId: '270419631491',
    projectId: 'readysethire-db',
    storageBucket: 'readysethire-db.firebasestorage.app',
    iosClientId: '270419631491-ub94343vltekp85skqbdt2s7mqn66537.apps.googleusercontent.com',
    iosBundleId: 'com.example.readysethire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-Ir-HKBjR5kOZoq_tRiFgI0_eO1M2Zg',
    appId: '1:270419631491:ios:fb864aee298f508726eab6',
    messagingSenderId: '270419631491',
    projectId: 'readysethire-db',
    storageBucket: 'readysethire-db.firebasestorage.app',
    iosClientId: '270419631491-ub94343vltekp85skqbdt2s7mqn66537.apps.googleusercontent.com',
    iosBundleId: 'com.example.readysethire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI0TMgEG-afSaihIi4XMMZYl3UVFn9HV0',
    appId: '1:270419631491:web:47b019619cc42ac426eab6',
    messagingSenderId: '270419631491',
    projectId: 'readysethire-db',
    authDomain: 'readysethire-db.firebaseapp.com',
    storageBucket: 'readysethire-db.firebasestorage.app',
    measurementId: 'G-L6VCB5BQX8',
  );
}
